//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace awesomeBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int ArticleID { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleBody { get; set; }
        public System.DateTime ArticleDate { get; set; }
        public string ArticleCreator { get; set; }
        public int ArticlePositiveAppeal { get; set; }
        public int ArticleNegativeAppeal { get; set; }
        public string ArticlePicture { get; set; }
        public string ArticleTags { get; set; }
        public Nullable<int> ArticleViews { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
