//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace awesomeBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public int ArticalID { get; set; }
        public string CommentBody { get; set; }
        public string CommentCreator { get; set; }
        public System.DateTime CommentDate { get; set; }
        public Nullable<int> CommentRating { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
